CREATE TABLE BOOK (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(255), ISBN VARCHAR(255), NBOFPAGE INTEGER, TITLE VARCHAR(255), UNITCOST FLOAT, PRIMARY KEY (ID))
CREATE TABLE EMPLOYEE (IDEMPLOYEE INTEGER NOT NULL, EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PRIMARY KEY (IDEMPLOYEE))
